[package]
name = "harpo"
version = "0.5.0"
authors = ["Thomas Locher <thomas.locher@dfinity.org>"]
edition = "2018"

[dependencies]
clap = "~2"
rand = "0.8.0"
num = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
sha2 = "0.9.8"
